version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
