FROM mysql:8.2.0
ENV MYSQL_ROOT_PASSWORD=root
#ENV MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
#WORKDIR /mysql_files
COPY ./databases/mysql_query.sql /docker-entrypoint-initdb.d/dummy_database.sql
EXPOSE 3306
